<MenuScreen>:
	on_enter: self.ids.dailyRoutineScreen.fill_todo_list()
	TabbedPanel:
		do_default_tab: False

		
		TabbedPanelItem:
			text: 'DailyRoutine'
			DailyRoutineScreen:
				id: dailyRoutineScreen
				
		
		TabbedPanelItem:
			text: 'StrategicGoals'
			StrategicGoalsScreen:

		TabbedPanelItem:
			text: 'Other'

		TabbedPanelItem:
			text: 'Analytics'

		TabbedPanelItem:
			text: 'Archive'

		TabbedPanelItem:
			text: 'Settings'